version: '3.3'

services:
  db:
    image: postgres
  web:
    image: pickmybruin/backend:latest
    command: bash initialize.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
